spring:
  application:
    name: docker-awesome
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lock?characterEncoding=UTF-8&connectionCollation=utf8mb4_bin
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: true
    database: mysql
  flyway:
    locations: classpath:db/migration
