version: '2'
services:
  redis-node-0:
    image: docker.io/bitnami/redis-cluster:6.2
    ports:
      - 6379:6379
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2'

  redis-node-1:
    image: docker.io/bitnami/redis-cluster:6.2
    ports:
      - 6380:6379
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2'

  redis-node-2:
    image: docker.io/bitnami/redis-cluster:6.2
    ports:
      - 6381:6379
    depends_on:
      - redis-node-0
      - redis-node-1
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_CLUSTER_CREATOR=yes'
