CREATE TABLE `sales_order` (
    `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `order_name` varchar(64) NOT NULL DEFAULT '' COMMENT '订单名称',
    `product_id` int(11) NOT NULL DEFAULT 0 COMMENT '产品id',
    `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='订单';
